### ISSUE TITLE
[PE-D] Task list issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-2/tp#145]
Steps:
1. task list done/, the app shows the only done task
2. task list undone/ the app still shows the only done task

I am wondering if it is better to enable step 2 to show all the undone tasks instead of the finished task?

![bug3_1.png](https://raw.githubusercontent.com/tsiyuk/ped/main/files/25641401-5fdb-4dc2-b3a0-df49d47f7eb0.png)

![bug3_2.png](https://raw.githubusercontent.com/tsiyuk/ped/main/files/bcffe321-48b2-42f4-9da8-dbca50fc096a.png)

![bug3_3.png](https://raw.githubusercontent.com/tsiyuk/ped/main/files/2461e007-910c-470b-aa59-ebd9fc02a8aa.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tsiyuk/ped#3

**Comment by jeffsieu** [comment]
Resolved by #129
