### ISSUE TITLE
[PE-D] Name can be number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-2/tp#173]
The name of a person can be changed to a number. Maybe it would be better to add a constraint on that?

![bug10.png](https://raw.githubusercontent.com/tsiyuk/ped/main/files/84bd71c1-3c60-443c-b5a4-51a89ba2f923.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tsiyuk/ped#10

**Comment by wlren** [comment]
Seems alright to me, sometimes can have multiple ppl with same names like ryan tan so numbers are another layer of identifiers?

**Comment by jeffsieu** [comment]
Yeah, I agree. If not Elon Musk cannot use this app for his son also.
